version: 2.1
jobs:
  get-token:
    working_directory: ~/workdir
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run:
          name: create service account key file
          command: echo ${GOOGLE_SERVICE_KEY} > key.json
          working_directory: ~/workdir
      - run:
          name: activate service account
          command: gcloud auth activate-service-account tokencreator@ca-tominaga.iam.gserviceaccount.com  --key-file=key.json
          working_directory: ~/workdir
      - run:
          name: export token as environment variables
          command: export TOKEN=`gcloud auth print-access-token --impersonate-service-account=firebase-adminsdk-tjdki@ca-tominaga.iam.gserviceaccount.com`
          working_directory: ~/workdir
  firebase-deploy:
    working_directory: ~/workdir
    docker:
      - image: gcr.io/cloud-builders/yarn
    steps:
      - checkout
      - run:
          name: print token
          command: echo ${TOKEN}
          working_directory: ~/workdir
      - run:
          name: yarn install
          command: yarn install
          working_directory: ~/workdir
      - run:
          name: firebase deploy with token
          command: firebase --token $TOKEN deploy
          working_directory: ~/workdir

workflows:
  version: 2
  deploy:
    jobs:
      - get-token
      - firebase-deploy:
          requires:
            - get-token
