version: 2.1
jobs:
  qa-job:
    working_directory: ~/workdir
    docker:
      - image: google/cloud-sdk:alpine
      - image: gcr.io/cloud-builders/yarn:16
    steps:
      - checkout
      - run:
          name: create service account key file
          command: echo ${GOOGLE_SERVICE_KEY} > key.json
          working_directory: ~/workdir
      - run:
          name: activate service account
          command: gcloud auth activate-service-account tokencreator@ca-tominaga.iam.gserviceaccount.com  --key-file=key.json
          working_directory: ~/workdir
      - run:
          name: yarn install
          command: yarn install
          working_directory: ~/workdir
      - run:
          name: deploy to firebase hosting
          command: yarn firebase --token (gcloud auth print-access-token --impersonate-service-account=firebase-adminsdk-tjdki@ca-tominaga.iam.gserviceaccount.com) deploy --only hosting
          working_directory: ~/workdir
workflows:
  qa-workflow:
    jobs:
      - qa-job
